packages:
  - 'mobile'
  - 'backend'
allowBuilds:
  '@langgraphjs/toolkit': set this to true or false
  esbuild: true
  msgpackr-extract: true
  protobufjs: false
minimumReleaseAgeExclude:
  - '@langchain/langgraph-sdk@1.9.19'
  - '@langchain/langgraph@1.3.7'
  - jest-expo@56.0.5
